### PR TITLE
fix arrow  position jank and add smoothing option and add inset / outset (IO keys)

### PR DESCRIPTION
**Pull request by thekeura**
…### Resolves

N/A, mostly quality of life stuff

### Proposed Changes
- The arrow tool is aligned to the cursor based on the center of the bottom edge
- You can now smooth the brush at varying thresholds instead of default
- You can inset and outset paths in the Reshape tool with the I / O keys
### Reason for Changes
The arrow tool had very janky positioning before, and I saw someone in the feedback channel want varying thresholds (forgot who)

### CODE REVIEW

**Comment by thekeura** [comment]
Also I did the commit on the wrong account (fail)

**Comment by RedMan13** [comment]
what does inset/outset mean..........

**Comment by RedMan13** [comment]
ignore the failed test it doesnt actually mean this is none-functional

**Comment by RedMan13** [comment]
ok yeah i dont see any issues with this :idk_man:

**Pull request merged**
